apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
      version: green
  template:
    metadata:
      labels:
        app: agent-service
        version: green
    spec:
      containers:
        - name: agent-service
          image: GCP_REGION-docker.pkg.dev/GCP_PROJECT_ID/my-agent-service-repo/agent-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: agent-service-db-secret
                  key: DATABASE_URL
