apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-service
      version: green
  template:
    metadata:
      labels:
        app: agent-service
        version: green
    spec:
      containers:
        - name: agent-service
          image: us-central1-docker.pkg.dev/moon-insurance/moon-insurance/agent-service:latest
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: agent-service-db-secret
                  key: DATABASE_URL
