apiVersion: v1
kind: Service
metadata:
  name: agent-service
spec:
  selector:
    app: agent-service
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: LoadBalancer # Makes the service accessible externally through a load balancer
